serial: serial.c
	gcc -g -Wall -std=c99 -o serial serial.c -lm

parallel: parallel.c
	mpicc -g -std=c99 -o parallel parallel.c -lm

auto_parallel: auto_parallel.c
	mpicc -g -std=c99 -o auto_parallel auto_parallel.c -lm


